In [20]:
import snscrape.modules.twitter as sntwitter
import pandas as pd
import datetime

In [21]:
# Creating list to append tweet data to
tweets_list2 = []
search_term = "marcos last will"

limit = 1000

years = [
    "2016",
    "2017",
    "2018",
    "2019",
    "2020",
    "2021",
    "2022"
]

months = [
    "01",
    "02",
    "03",
    "04",
    "05",
    "06",
    "07",
    "08",
    "09",
    "10",
    "11",
    "12"
]

end_of_month_days = [
    "31",
    "28",
    "31",
    "30",
    "31",
    "30",
    "31",
    "31",
    "30",
    "31",
    "30",
    "31"
]

In [27]:
# Using TwitterSearchScraper to scrape data and append tweets to list

for year in years:
    for month in range(len(months)):
        print(f"Starting with {year}-{months[month]}-01")
        for i, tweet in enumerate(
                sntwitter.TwitterSearchScraper(f'{search_term} since:{year}-{months[month]}-01 until:{year}-{months[month]}-{end_of_month_days[month]}').get_items()):
            
            if i >= limit:
                print(f"Exceeded {limit} tweets in {year}-{months[month]}")
                break

            tweets_list2.append([
                tweet.id,
                tweet.url,
                search_term,
                tweet.user.username,
                tweet.user.displayname,
                tweet.user.rawDescription,
                "",
                tweet.user.created,
                tweet.user.friendsCount,
                tweet.user.followersCount,
                tweet.user.location,
                tweet.rawContent,
                "",
                "",
                tweet.date,
                "",
                "",
                tweet.likeCount,
                tweet.replyCount,
                tweet.retweetCount,
                tweet.quoteCount,
                tweet.media,
                tweet.inReplyToUser,
                tweet.inReplyToTweetId,
                tweet.retweetedTweet,
                tweet.quotedTweet,
                tweet.mentionedUsers,
                tweet.vibe,
                tweet.conversationId,
            ])
        print(f"Done with {year}-{months[month]}-{end_of_month_days[month]}")

Starting with 2016-01-01
Done with 2016-01-31
Starting with 2016-02-01
Done with 2016-02-28
Starting with 2016-03-01
Done with 2016-03-31
Starting with 2016-04-01
Done with 2016-04-30
Starting with 2016-05-01
Done with 2016-05-31
Starting with 2016-06-01
Done with 2016-06-30
Starting with 2016-07-01
Done with 2016-07-31
Starting with 2016-08-01
Done with 2016-08-31
Starting with 2016-09-01
Done with 2016-09-30
Starting with 2016-10-01
Done with 2016-10-31
Starting with 2016-11-01
Done with 2016-11-30
Starting with 2016-12-01
Done with 2016-12-31
Starting with 2017-01-01
Done with 2017-01-31
Starting with 2017-02-01
Done with 2017-02-28
Starting with 2017-03-01
Done with 2017-03-31
Starting with 2017-04-01
Done with 2017-04-30
Starting with 2017-05-01
Done with 2017-05-31
Starting with 2017-06-01
Done with 2017-06-30
Starting with 2017-07-01
Done with 2017-07-31
Starting with 2017-08-01
Done with 2017-08-31
Starting with 2017-09-01
Done with 2017-09-30
Starting with 2017-10-01
Done with 2017-10-31
Starting with 2017-11-01
Done with 2017-11-30
Starting with 2017-12-01
Done with 2017-12-31
Starting with 2018-01-01
Done with 2018-01-31
Starting with 2018-02-01
Done with 2018-02-28
Starting with 2018-03-01
Done with 2018-03-31
Starting with 2018-04-01
Done with 2018-04-30
Starting with 2018-05-01
Done with 2018-05-31
Starting with 2018-06-01
Done with 2018-06-30
Starting with 2018-07-01
Done with 2018-07-31
Starting with 2018-08-01
Done with 2018-08-31
Starting with 2018-09-01
Done with 2018-09-30
Starting with 2018-10-01
Done with 2018-10-31
Starting with 2018-11-01
Done with 2018-11-30
Starting with 2018-12-01
Done with 2018-12-31
Starting with 2019-01-01
Done with 2019-01-31
Starting with 2019-02-01
Done with 2019-02-28
Starting with 2019-03-01
Done with 2019-03-31
Starting with 2019-04-01
Done with 2019-04-30
Starting with 2019-05-01
Done with 2019-05-31
Starting with 2019-06-01
Done with 2019-06-30
Starting with 2019-07-01
Done with 2019-07-31
Starting with 2019-08-01
Done with 2019-08-31
Starting with 2019-09-01
Done with 2019-09-30
Starting with 2019-10-01
Done with 2019-10-31
Starting with 2019-11-01
Done with 2019-11-30
Starting with 2019-12-01
Done with 2019-12-31
Starting with 2020-01-01
Done with 2020-01-31
Starting with 2020-02-01
Done with 2020-02-28
Starting with 2020-03-01
Done with 2020-03-31
Starting with 2020-04-01
Done with 2020-04-30
Starting with 2020-05-01
Done with 2020-05-31
Starting with 2020-06-01
Done with 2020-06-30
Starting with 2020-07-01
Done with 2020-07-31
Starting with 2020-08-01
Done with 2020-08-31
Starting with 2020-09-01
Done with 2020-09-30
Starting with 2020-10-01
Done with 2020-10-31
Starting with 2020-11-01
Done with 2020-11-30
Starting with 2020-12-01
Done with 2020-12-31
Starting with 2021-01-01
Done with 2021-01-31
Starting with 2021-02-01
Done with 2021-02-28
Starting with 2021-03-01
Done with 2021-03-31
Starting with 2021-04-01
Done with 2021-04-30
Starting with 2021-05-01
Done with 2021-05-31
Starting with 2021-06-01
Done with 2021-06-30
Starting with 2021-07-01
Done with 2021-07-31
Starting with 2021-08-01
Done with 2021-08-31
Starting with 2021-09-01
Done with 2021-09-30
Starting with 2021-10-01
Done with 2021-10-31
Starting with 2021-11-01
Done with 2021-11-30
Starting with 2021-12-01
Done with 2021-12-31
Starting with 2022-01-01
Done with 2022-01-31
Starting with 2022-02-01
Done with 2022-02-28
Starting with 2022-03-01
Done with 2022-03-31
Starting with 2022-04-01
Done with 2022-04-30
Starting with 2022-05-01
Done with 2022-05-31
Starting with 2022-06-01
Done with 2022-06-30
Starting with 2022-07-01
Done with 2022-07-31
Starting with 2022-08-01
Done with 2022-08-31
Starting with 2022-09-01
Done with 2022-09-30
Starting with 2022-10-01
Done with 2022-10-31
Starting with 2022-11-01
Done with 2022-11-30
Starting with 2022-12-01
Done with 2022-12-31

In [70]:
# Creating a dataframe from the tweets list above
df = pd.DataFrame(tweets_list2, columns=[
    "Tweet ID",
    "Tweet URL",
    "Keywords",
    "Account handle",
    "Account name",
    "Account bio",
    "Account type",
    "Joined",
    "Following",
    "Followers",
    "Location",
    "Tweet",
    "Tweet translated",
    "Tweet type",
    "Date posted",
    "Screenshot",
    "Content type",
    "Likes",
    "Replies",
    "Retweets",
    "Quote tweets",
    "Media",
    "In reply to user",
    "In reply to tweet ID",
    "Retweeted tweet",
    "Quoted tweet",
    "Mentioned Users",
    "Vibe",
    "Conversation ID",
])

In [71]:
# Classifying content type
import numpy as np

conditions = [
    (df['In reply to tweet ID'].notnull()),
    (df['Retweeted tweet'].notnull()),
    (df['Quoted tweet'].notnull()),
    (df['Media'].notnull()),
]

values = ['Reply', 'Reply', 'Reply', 'MEDIA']

df["Tweet type"] = np.select(conditions, values, default='Text')

df["Tweet type"].value_counts()

Text     569
Reply    559
MEDIA     78
Name: Tweet type, dtype: int64

In [73]:
df[df['Tweet type'] == 'MEDIA'].head()

,Tweet ID,Tweet URL,Keywords,Account handle,Account name,Account bio,Account type,Joined,Following,Followers,...,Retweets,Quote tweets,Media,In reply to user,In reply to tweet ID,Retweeted tweet,Quoted tweet,Mentioned Users,Vibe,Conversation ID
28,730455073050894337,https://twitter.com/anglcsdno/status/730455073...,marcos last will,anglcsdno,Angelica Sedano,,,2010-07-19 09:53:24+00:00,459,563,...,0,0,https://twitter.com/anglcsdno,730454519050469376,NaN,None,None,None,7.304545e+17,NaN
59,801784101120245760,https://twitter.com/CJMeneses_/status/80178410...,marcos last will,CJMeneses_,Jayce Castillon,m e d y o s i n g l e,,2016-06-23 13:22:51+00:00,103,37,...,0,0,https://twitter.com/nlsgllgo,801783243494158336,NaN,None,None,None,8.017643e+17,NaN
89,798694941476065280,https://twitter.com/newstogoGNTV/status/798694...,marcos last will,newstogoGNTV,News To Go,This is the official account of News To Go hos...,,2012-06-29 08:17:22+00:00,291,35157,...,0,0,https://twitter.com/newstogoGNTV,798694928847015936,NaN,None,None,None,7.986949e+17,NaN
172,876777103454121984,https://twitter.com/rowmansss/status/876777103...,marcos last will,rowmansss,R. ☕,"one vanilla latte, hot, no foam. (he/him) \nSW...",,2010-08-20 16:45:45+00:00,278,461,...,0,0,https://twitter.com/rowmansss,876776580030152704,NaN,None,None,None,8.767766e+17,NaN
226,1273201544565940224,https://twitter.com/Rosie_elleSB19/status/1273...,marcos last will,Rosie_elleSB19,Mochi,SB19 fan account 💙\nKen Suson 🐣 and OT5 💙,,2020-04-01 10:42:43+00:00,192,85,...,0,0,https://twitter.com/_aelsrim,1272943424753119233,NaN,None,None,None,1.272769e+18,NaN

In [74]:
df.to_csv(f'data.csv')